collections:
- devtools
- apps
- clients
url: https://tworingsoft.com
exclude: [ Makefile, Brewfile, LICENSE, Gemfile, Gemfile.lock, README.md, .gitignore, vendor ]
tag_page_layout: tag_page
tag_page_dir: blog/tag
tag_feed_layout: tag_feed
tag_feed_dir: blog/tag